#!/usr/bin/python3
"""
This module contains comman breaking keywords and events to search for in the fb api
"""
search_words = [
'bboy',
'b-boy',
'breakin battle',
'breaking battle',
'b-boy cypher',
'bboy cypher',
'break battle',
'freestyle session',
'battle cypher',
'cypher battle',
'smoke battle',
'circle battle',
'bgirl',
'b-girl',
'battle of the year',
'redbull bc one',
"0229 Dance Battle - Vol. 6",
"11 Aniversario De Latin Break",
"1212 Breaksgiving",
"299 Jam",
"3 Semana Integracao Hip Hop",
"3D Bboys 23rd Anniversary Jam",
"4th Opole Dance Festival",
"5 Aniverzario Suacha Estilo",
"524 Skills 2017",
"7th Anniversary Diademaica Crew",
"8 Encontro Nacional De Danca Lafaiete",
"90 Flavaz Jam For bie",
"90 Flavaz Jam",
"Able Respect Battle - Vol. 2",
"Age-Based Breakin Battle",
"Agromeraarte - Vol. 3",
"Alpha Break 2017",
"Aniversario Murderouz Crew",
"Aniversario Tribuen Un Asalto Por La Paz",
"Ap Crew Brother Hood - Vol. 3",
"Aurora Battle - Vol. 3",
"B-Brave",
"Back 2 School Battle",
"Back To School 3",
"Back To The Basix - Vol. 2",
"Baltic Breaks & Waves - Vol. 3",
"Basement Battles",
"Bashville Stampede More Than A Jam ",
"Batalha Da Cultura",
"Batalha Da Prova",
"Batalha Das Gang's 2017",
"Batalha De Breaking Integracao Hip Hop",
"Batalha Do Cerrado",
"Batalla Del Barrio 7",
"Battle Choc",
"Battle City - Vol. 2",
"Battle Dojo Hong Kong City 2017",
"Battle Family Break",
"Battle Fever - Vol. 7",
"Battle For Boston 2017",
"Battle Hip-Hop / Break",
"Battle In Taoyuan Final 2017",
"Battle In The House - Vol. 13",
"Battle J2K",
"Battle Kid's 2017",
"Battle Kids / Breakdance",
"Battle  School 14 - World Final Breakdance",
"Battle Of Est 2017",
"Battle Of Minga 2017",
"Battle Of The Best Thessaloniki 2017",
"Battle Of The Kids 2018 - Qualifier Germany",
"Battle OPsession 2018",
"Battle Smoke The Flava",
"Battle Tested 6",
"Battle Urban Talent - Vol. 4",
"Bboy Contest International - Vol. 10",
"Bboy Factory 6th Anniversary",
"Bboy Fight",
"Bboy France Championnat De Break-Dance 2017",
"Bboy Reunion X Skillz Hawaii",
"Bboy Smoke",
"Bboyz Battle",
"Bcs - Vol. 4",
"BDE Cypher",
"Beats Motel 3",
"Belgian Championships Breakdance",
"Bet Money - Vol. 1",
"BFC - Hip Hop Festival",
"Bitva O Trun 2017",
"Bitwa Na Taniec - Vol. 9",
"Black Luv",
"Bootcamp Battles",
"Born To Dance Internacional Session 6",
"Break A Leg 2018",
"Break Central - Vol. 4",
"Break Dance Battle",
"Break Down The House",
"Break LA - Vol. 12",
"Break The Floor Africa 2017",
"Break The Floor America Latina 2017",
"Break The Norm",
"Break The Skill's - Vol. 4",
"Break YoSelf Fool 11",
"Break: The Battle",
"Breakdance Battle",
"Breaking Masters Riga Preselection",
"Breaking Na Pista 2017",
"Breaking Suriname 2017",
"Breaking The Border - Vol. 6",
"Breakleague J3 + Fluido Jam France Qualifier 2017",
"Breaks Kru 21 Year Anniversary",
"Breaksm / Ultimate B-Boy Jam Oulu Eliminations 2017",
"BreakSP Battle 2017",
"Breezer Vivid Shuffle: Mumbai Regional Rounds",
"Bring The Toast",
"Brooklyn's Finest Kids - Vol. 2",
"BS Battle 2017",
"BTL - Powermoves Championship Series",
"CABC Filtro Departamental",
"Call Out Bboy Battle",
"Callout Break Dance Battle",
"Campeonato De Break Dance - La Conquista",
"Can I Get A Soul Clap 2017",
"Carinthian X Break 2018",
"Catch Wreck",
"Central America Breaking Championship 2017",
"Central India Cyphers - Vol. 4",
"Challenge Nepal 2017",
"Champions Of Ring",
"Chess Boxin - Vol. 2",
"Circle Battle 2017",
"Circle Of Bobby",
"Circle Of Fire 2017",
"Clash Of Styles Bboy Battle",
"Classic Under 2017",
"Clutchfest 2017",
"Cola Com Nois Que E Cypher - Vol. 3",
"College High - Vol. 13",
"Come And Get It",
"Community Access End Of The 2017",
"Cone Contest",
"Crew Battle show",
"Cube - Vol. 5",
"Cup Ian Hipfest Asean",
"Cup Ian Hipfest Asean",
"Cypher In Da House",
"Cypher Of The Year 2017",
"Cypher Town Break Battle 2018",
"Dance & Style Battle 2018",
"Dance Parade",
"Dance With Wolves",
"Debate Bboys En Bolivia 2017",
"Delta Connection Workshop Jam Series + Bboy Wing - Part 2",
"Do Not Cross The Yellow Line Jam",
"Dojdi Sa Rozmrazit 2018",
"EDA Battle Chalon",
"Egypt Breaking 2",
"Enter The Circle 2017",
"Enter The Stage Jam - Vol. 4",
"Entering ShaoLynn",
"Estilo Libre",
"Evento A Beneficio De Bboy Lucho Mario",
"Evento Breaking A Beneficio De Bboy Lucho Mario",
"Express Yourself",
"Extreme Evolution 2017",
"Feel Da Bounce 2017",
"Festival Hip-Hope",
"Festival J2K 2017",
"Filtro - La Batalla Del Valle",
"Flon Battle 2017",
"Floor Rippers + Break Mission",
"Floor Wars 2",
"Floor Wars Italy 2018",
"Floor Wars Tunisia 2017",
"Floorthodox 3 Year Aniversary",
"Flow Of The Elements 2017",
"Fly Battle 2017",
"For Your Soul 10",
"For Your Soul 10",
"Free Mind Kids Jam 2017",
"Freestyle On The Block - Vol. 5",
"Freestyle Session 20th Year Anniversary - The Return Of The Crew Battle",
"Freestyle Session Kids Battles",
"Freestyle Session World Finals 2017",
"Fresh Floor - Vol. 4",
"From The Street Battle 2017",
"Fryshuset Halloween GetDown",
"Furious Styles Crew 24year Anniversary",
"FWBDS Breaking Cup",
"GC Battles 5 - Total Eclipse",
"Giamik Raia Breaking/Hip Hop Battle",
"Golden Breaking Championship",
"Golden King 2017",
"Greenvision Blockhouse 4",
"Groove In City - Vol. 1",
"Groove Session 2017",
"Ground Conference 4 – Urban Dance Battle",
"Ground Killaz 7",
"Halley Jam 2017 - Halley Crew 14th Anniversary",
"Halloween Breaking Jam 2017",
"Halloween Jam 2017",
"HHI Netherlands Battles & Urban Moves Dance Workshops",
"Hip Hop Conciencia",
"Hip Hop Dance Exchange",
"Hip Hop Kemp 2018",
"Hip Hop Revolution Dance Festival 2017",
"Hip Hop Street - Victor Larco Herrera",
"Hip Hop Summit 2018",
"Hip Hop Weekend 2017",
"Hip-Hop 4 Toys",
"Hoa Thuong Cup 2017",
"House Of Battle 2",
"House Of Villains",
"I Love Cyphers Malaga",
"I Pity The Foll",
"Icbeatz 2.0",
"Ice Breakers Aniversario 2017",
"IDO European Hip Hop, Electric Boogie And Break Dance Championships 2018",
"IDO European Hip Hop, Electric Boogie And Break Dance Championships 2020",
"IDO World Hip Hop, Electric Boogie And Break Dance Championships 2017",
"IDO World Hip Hop, Electric Boogie And Break Dance Championships 2018",
"IDO World Hip Hop, Electric Boogie And Break Dance Championships 2019",
"IDO World Performing Art And Street Dance Cups VI. Artis Games",
"IDS Born To Battle Competition",
"III Crazy Beat - Batalha De Breaking",
"Il Breaks 13",
"In The Midst Of The Cypher 2017",
"Inner City Jam",
"Intensity The Finale: Antique Session",
"Interkult Battle Day - Urban Dance Jam & Battles",
"Interschool 2018",
"IPhlow 5",
"It's Battle Time - Vol. 3",
"Italy Best Flava 2017",
"IX Batalla En La Capital Internacional",
"Jahoda Dzem 2017 - 5th Anniversary",
"Jam Costa Escondida",
"Joint & Jam 2018",
"Just For Funs BBoy Battle - Vol. 2",
"K-Battle 2017",
"KGB Battle Mania 29",
"KGS Party 7",
"KIC Breaks 2017",
"Kids Noise",
"Kids Of The Future - Vol. 3",
"Kids Power Jam",
"Kings Of Monsters 2017",
"Kings Of The Midwest 5",
"Kings Of The Street - Vol. 8",
"Knock Out Breaking Battle 2017",
"Knowledge Pays",
"KNP 78 Funk Circle - Vol. 2",
"KOD Italy 2018",
"KOD UK 2017",
"Kombate Mortal 3",
"La Batalla Del Sur",
"La Batalla Del Valle 2017",
"La Jam Central Presenta A Mariela Vallejos",
"La Jamada 3ra Sesion",
"LCB Choose Your Destiny 2017",
"Let's Funk-India Battleground Battle - Vol. 4",
"Lille Battle Pro",
"Line Of Attack - Vol. 3",
"Lisadowa Rewolucja",
"Lithuanian Cup 2017",
"Live It Live (Neo Motion Anniversary)",
"Lons International Battle",
"Ma Lu Contest",
"Makura Festival Dance Battle",
"Mano A Mano",
"Mash 2017",
"Master Of Jam - Vol. 3",
"MDM 2.0",
"Me Gusta Halloween Sokiu Kovos",
"Michigan Collegiate Bboy Conference 2017",
"Mortal Kombat 2017",
"Nederlandse Breakdance League 2017",
"Netherlands Hip Hop Dance Championship 2018",
"Never Back Down Battle",
" Kids On The Block 2017",
"Next Generation Jam 2017",
"Neya-1 - Vol. 9",
"Night Battle - Vol. 4",
"No Enemies",
"NOK Aniversario 10",
"Not For Sale: Hip Hop Jam",
"NRG Battles",
"Nunkun Styles",
"Occitanie Battle Pro",
"Ocean 2 Sky Battles",
"Omsim Dance Battle",
"One Day One Bboy",
"Open Dance De Hip Hop Y Break Dance 2017",
"Orion Jam 2017",
"Ostrowski Styl 2017",
"Path To Flow Jam 2017",
"PBS Day - Vol. 2",
"Peace Jam 2",
"Pessac Battle Arena 2017",
"Por Verte Sonreir",
"Pre Christmas Battle",
"Primer Campeonato Nacional De Baile Chiriguana",
"Proovin' Grounds",
"Pune Popping Festival - Vol. 2",
"Puzzle Party - Vol. 4",
"Quality Check",
"Queen & King of Style - Vol. 26",
"Quinto Aniversario SDH Crew",
"R!NG 11",
"Random Battle 2017",
"Raw Diamondzz 2.0",
"RAWR - Kids Battle",
"Ready 2 Rumble XIV",
"Reborn Halloween Party II",
"Red Bull BC One Austria 2018",
"Red Bull BC One Camp Holland 2017",
"Red Bull BC One Last Chance Cypher 2017",
"Red Bull BC One Viewing Party / 1vs1 Breaking Battle",
"Red Bull BC One World Final 2017",
"Regio Block Party 2017",
"Return Of The Sickness: The Human Centipede",
"Revolution Dance Contest 2017",
"Rhythmic Damage XII",
"Ride The Breaks Hip Hop Cultural Festival 2017",
"Rock Da Jam Senior",
"Rock The Block - Vol. 5",
"Rockaforte Battle",
"Rockeando El Piso - Vol. 2",
"Rockin In The Free World Jam - Vol. 4",
"Rocking Star 2017",
"Roda Cultural Cidade De Deus - Vol. 48",
"Room 100 - Vol. 5",
"Salto City Break Battle 2017",
"SAS Contest",
"Saxonz Dance Off - X-Mas Edition",
"Scape Radikal Forze Jam 2018",
"Scenario Battle",
"SDC North East Street Dance Championships 2018",
"SDC North West Street Dance Championships 2018",
"Shah Alam Cypher Call - Vol. 3",
"Shamrock Cypher - Vol. 4",
"Show Your Skillz 2018",
"Simii Battle",
"Sin Fronteras 2017",
"Sin Fronteras Urban Dance 2017",
"Sintiendo El Nectar De Los Dioses 2",
"Sip The Juice 3 - Juse Crew 17th Year Anniversary",
"Six 1 Cypher - Vol. 9",
"Slammed Society 2017",
"Smoke The Circle - Vol. 3",
"Smoked In Ohio 4",
"Somos Pasion, Somos Danza Concurso Interno",
"Sopitas Con Huevo Aniversario 11",
"Soul Connection",
"Soul Techniquex Crew 8th Anniversary Bboy Jam",
"Sounds From The Underground 3",
"South Rocks - Vol. 5",
"Southwest In Motion Battles",
"Spin Off 1",
"Spin Off 2",
"Spin Off 3",
"Spin Off 4",
"Spin Off Finale",
"Stage Break, Street, Ragga, Enfants, Ados",
"Station Of Street Battle Jam - Vol. 2",
"Straight From The Street - Vol. 2",
"Street Arts Day",
"Street Battle + Bboy Battle - Mistrovstvi CR",
"Street Dance Groove Contest",
"Street Groove Jam - Vol. 4",
"Street Legacy 2017",
"Street Vibez Battle Edition",
"Style Break Battle Anniversary",
"Style Spectrum 2017",
"Stylowe Uderzenie - Vol. 16",
"Supa Breaking",
"Super Das Ruas",
"Support The Fam Benefit Jam",
"Supreme Circle Of Bobby",
"Swift Charakterz 10th Year Anniversary Jam",
"Swiss IDO Breakdance Championship 2018",
"Synchronicity Bboy Battle",
"TAF Deutsche Meisterschaft Breakdance",
"Taipei Bboy City World Final 2017",
"Take 2 Bboy & Dance Party",
"TCS Break Dance Tournament 2017 - Round 4",
"Teamka 2017 - 14th Urban Dance Contest",
"Tech Styles 4",
"TGIF Get Down - Halloween Edition",
"The 3rd Wheel Jam - UK Kids Breakin' League",
"The B.B.I.E. Union 2017",
"The Battle For Queens",
"The Break Day 11",
"The Circle",
"The Circle Of Dancers",
"The Doom Romm Halloween Jam",
"The First Jam - Vol. 6",
"The Fucking Flavor Qualifier El Pastel 2017",
"The Legits Blast 2018",
"The Legits Blast Winter Festival 2018",
"The Melting Pot 2 - The Never Ending Jam",
"The National Dance Competition",
"The Official B.Kidz Battle",
"The Refuge",
"The Session VIII",
"The Soul Flows",
"The Square Contest - Vol. 4",
"The Stage Break",
"TheUrban Kidz Battle",
"Usaf Bboy battle",
"Valstreet United Battle",
"Vandal Battle",
"Versus VII",
"Virada Jovem 2017",
"Viva Break - Vol. 8",
"Watch Out – Guez Whoz Bak 2017",
"Weekend 1.7",
"West Coast Rockers Anniversary 2017",
"West Country Clash 2018",
"Who Can Roast The Most Denver",
"Who’s The Beast - Vol. 3",
"Winter Soul Break - Vol. 2",
"Wirujaca Strefa 2017",
"You Got Scared",
"Youth Olympic Games 2018",
"Yudisthl Battle - Vol. 1",
"Zulu Nation 44",
]


desc_words = [
    'bboy',
    'b-boy',
    'cypher'
    'freestyle session',
    'bgirl',
    'b-girl'
]
